"""empty message

Revision ID: 40b0eaece60b
Revises: 2c2272e140e2
Create Date: 2024-09-15 14:42:46.015980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b0eaece60b'
down_revision: Union[str, None] = '2c2272e140e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__url_storage__id'), 'url_storage', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__url_storage__id'), 'url_storage', type_='unique')
    # ### end Alembic commands ###
