"""empty message

Revision ID: 2c2272e140e2
Revises: 
Create Date: 2024-09-15 14:30:57.025704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2272e140e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_storage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__url_storage')),
    sa.UniqueConstraint('id', name=op.f('uq__url_storage__id')),
    sa.UniqueConstraint('name', name=op.f('uq__url_storage__name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_storage')
    # ### end Alembic commands ###
