"""empty message

Revision ID: 9ff43f8c9d0c
Revises: 
Create Date: 2024-09-27 13:40:59.781505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff43f8c9d0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('gen_random_uuid()'), autoincrement=True, nullable=False),
    sa.Column('russian', sa.TEXT(), nullable=False),
    sa.Column('english', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__word')),
    sa.UniqueConstraint('english', name=op.f('uq__word__english')),
    sa.UniqueConstraint('id', name=op.f('uq__word__id')),
    sa.UniqueConstraint('russian', name=op.f('uq__word__russian'))
    )
    op.create_table('card',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('gen_random_uuid()'), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rarity', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__card__user_id__user')),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name=op.f('fk__card__word_id__word')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__card')),
    sa.UniqueConstraint('id', name=op.f('uq__card__id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('word')
    # ### end Alembic commands ###
